name: Update Language Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch Commit-Based Language Stats
        uses: Mocdan/git-language-stats-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          USERNAME: "TheRickyZhang"
          # EXCLUDE_REPOS: "repo1,repo2"  # Optional: add any repos to exclude

      - name: Commit & Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "Updated language stats" || exit 0
          git push
